# Generated by Django 5.1.7 on 2025-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='headline_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='source_options',
            field=models.JSONField(default=list),
        ),
    ]
